apiVersion: v1
data:
  APP_ENV: staging
  CACHE_ENABLED: "true"
  CACHE_TTL: "300"
  DB_HOST: staging-db.internal
  LOG_LEVEL: info
  MAX_CONNECTIONS: "50"
  TIMEOUT: "60"
  VERSION: 1.1.0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APP_ENV":"staging","CACHE_ENABLED":"true","CACHE_TTL":"300","DB_HOST":"staging-db.internal","LOG_LEVEL":"info","MAX_CONNECTIONS":"50","TIMEOUT":"60","VERSION":"1.1.0"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"sample-app","environment":"staging","managed-by":"driftlens"},"name":"sample-app-config","namespace":"staging"}}
  creationTimestamp: "2026-08-15T06:36:08Z"
  labels:
    app: sample-app
    environment: staging
    managed-by: driftlens
  name: sample-app-config
  namespace: staging
  resourceVersion: "736"
  uid: 4f9f1f35-79b9-484d-a31b-a873c86286a0
