apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"sample-app","environment":"dev","managed-by":"driftlens"},"name":"sample-app","namespace":"development"},"spec":{"ports":[{"name":"http","port":80,"targetPort":80}],"selector":{"app":"sample-app","environment":"dev"},"type":"ClusterIP"}}
  creationTimestamp: "2026-08-15T06:36:02Z"
  labels:
    app: sample-app
    environment: dev
    managed-by: driftlens
  name: sample-app
  namespace: development
  resourceVersion: "717"
  uid: 8e884f6f-cdce-4d44-951b-6a41ca814c30
spec:
  clusterIP: 10.108.78.251
  clusterIPs:
  - 10.108.78.251
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-app
    environment: dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
