apiVersion: v1
kind: Service
metadata:
  name: driftlens-deep-frontend
  labels:
    app: driftlens-deep
    component: frontend
spec:
  selector:
    app: driftlens-deep
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort
